function mdl = build_gla_model(mdl)
%BUILD_GLA_MODEL  Construct the AGLAS adaptive gust load alleviation model.
%
%   build_gla_model
%   mdl = BUILD_GLA_MODEL(name)
%
%   Builds the Simulink model from the matrices AGLAS_SIM_SETUP puts in the
%   base workspace, then saves and opens it.
%
%   Usage
%       aglas_sim_setup;           % nominal
%       build_gla_model;           % creates and opens aglas_gla.slx
%       sim('aglas_gla');
%
%   To fly the same controller against a degraded surface:
%       aglas_sim_setup('baseline', 0.3, 5, 0.4);   % 40 % effectiveness
%       sim('aglas_gla');
%
%   The model is generated by a script rather than committed as a binary .slx
%   so that it can be reviewed in a diff, regenerated against changed design
%   matrices, and kept honest: every gain in it traces back to the same
%   functions the pure-MATLAB pipeline uses.
%
%   Architecture
%
%     gust ---------------------------------+
%                                           v
%     u_sat --> [ PLANT  8 states ] --> y (strain, tip accel), z (moment, tip)
%                    ^                      |
%                    |                      v
%                    |             [ ESTIMATOR 9 states ]  (structure + gust)
%                    |                      |
%                    |            +---------+----------+
%                    |            |                    |
%                    |       xhat (all)            w_hat (gust)
%                    |            |                    |
%                    |     [ -K ] |              [ REFERENCE MODEL ]
%                    |        |   |                    | xm
%                    |    u_lqg   +--------+-----------+
%                    |        |            v
%                    |        |    [ ADAPT LAW ] -> [ 1/s ] -> theta
%                    |        |                                 |
%                    |        |            [ u_ad = theta'*phi ]
%                    |        |                     |
%                    |        +---(+)---------------+
%                    |             |
%                    +--[SAT]--[RATE LIMIT]--+
%
%   Solver: fixed step ode4. The rate limiter is a stateful nonlinearity whose
%   output depends on the previously accepted step, so a variable-step solver
%   that rejects and retries steps can corrupt it.

    if nargin < 1 || isempty(mdl)
        mdl = 'aglas_gla';
    end

    if evalin('base', '~exist(''AGLAS'', ''var'')')
        error('build_gla_model:noSetup', ...
              'Run aglas_sim_setup first; it puts the design matrices in the base workspace.');
    end
    S = evalin('base', 'AGLAS');
    ns = S.n_states;
    na = S.n_aug;

    % Start from a clean slate.
    if bdIsLoaded(mdl), close_system(mdl, 0); end
    new_system(mdl);

    add = @(src, name, pos) add_block(src, [mdl '/' name], 'Position', pos);

    % ------------------------------------------------------------ sources
    add('simulink/Sources/From Workspace', 'Gust', [30 300 110 330]);
    set_param([mdl '/Gust'], 'VariableName', 'AGLAS.gust', ...
              'SampleTime', '0', 'Interpolate', 'on', ...
              'OutputAfterFinalValue', 'Holding final value');

    % ------------------------------------------------------------- plant
    add('simulink/Signal Routing/Mux', 'PlantIn', [180 205 185 335]);
    set_param([mdl '/PlantIn'], 'Inputs', '2');

    add('simulink/Continuous/State-Space', 'Plant', [220 230 330 310]);
    set_param([mdl '/Plant'], ...
        'A', 'AGLAS.plant.A', 'B', 'AGLAS.plant.B', ...
        'C', 'AGLAS.plant.C', 'D', 'AGLAS.plant.D', ...
        'X0', 'AGLAS.plant.x0');

    add('simulink/Signal Routing/Demux', 'PlantOut', [370 245 375 295]);
    set_param([mdl '/PlantOut'], 'Outputs', '[2 2]');

    % --------------------------------------------------------- estimator
    add('simulink/Signal Routing/Mux', 'EstIn', [430 355 435 445]);
    set_param([mdl '/EstIn'], 'Inputs', '2');

    add('simulink/Continuous/State-Space', 'Estimator', [480 375 590 435]);
    set_param([mdl '/Estimator'], ...
        'A', 'AGLAS.est.A', 'B', 'AGLAS.est.B', ...
        'C', 'AGLAS.est.C', 'D', 'AGLAS.est.D', ...
        'X0', 'AGLAS.est.x0');

    % Split the estimate into the structural part and the gust estimate.
    add('simulink/Signal Routing/Selector', 'PickStruct', [640 380 690 410]);
    set_param([mdl '/PickStruct'], 'NumberOfDimensions', '1', ...
        'IndexOptions', 'Index vector (dialog)', ...
        'Indices', sprintf('1:%d', ns), 'InputPortWidth', num2str(na));

    add('simulink/Signal Routing/Selector', 'PickGust', [640 450 690 480]);
    set_param([mdl '/PickGust'], 'NumberOfDimensions', '1', ...
        'IndexOptions', 'Index vector (dialog)', ...
        'Indices', num2str(S.idx_gust), 'InputPortWidth', num2str(na));

    % ------------------------------------------------------ baseline gain
    add('simulink/Math Operations/Gain', 'Kgain', [660 300 720 340]);
    set_param([mdl '/Kgain'], 'Gain', '-AGLAS.K', ...
              'Multiplication', 'Matrix(K*u)');

    % ------------------------------------------------- MRAC reference model
    add('simulink/Continuous/State-Space', 'RefModel', [740 450 850 510]);
    set_param([mdl '/RefModel'], ...
        'A', 'AGLAS.ref.A', 'B', 'AGLAS.ref.B', ...
        'C', 'AGLAS.ref.C', 'D', 'AGLAS.ref.D', ...
        'X0', 'AGLAS.ref.x0');

    % ------------------------------------------------------ adaptive law
    add('simulink/Signal Routing/Mux', 'AdaptIn', [900 520 905 620]);
    set_param([mdl '/AdaptIn'], 'Inputs', '3');

    add('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
        'AdaptLaw', [940 550 1040 590]);
    set_param([mdl '/AdaptLaw'], 'MATLABFcn', 'aglas_adapt_law', ...
              'OutputDimensions', num2str(ns));

    add('simulink/Continuous/Integrator', 'ThetaInt', [1080 550 1110 590]);
    set_param([mdl '/ThetaInt'], 'InitialCondition', sprintf('zeros(%d,1)', ns));

    add('simulink/Signal Routing/Mux', 'UadIn', [900 640 905 700]);
    set_param([mdl '/UadIn'], 'Inputs', '2');

    add('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
        'Uadaptive', [940 655 1040 695]);
    set_param([mdl '/Uadaptive'], 'MATLABFcn', 'aglas_u_adaptive', ...
              'OutputDimensions', '1');

    % A switch on the adaptive branch, so the same model runs plain LQG.
    add('simulink/Math Operations/Gain', 'AdaptOn', [1080 660 1130 690]);
    set_param([mdl '/AdaptOn'], 'Gain', 'AGLAS.adapt_on');

    % ------------------------------------------------- command and actuator
    add('simulink/Math Operations/Sum', 'SumU', [1180 380 1200 400]);
    set_param([mdl '/SumU'], 'Inputs', '++', 'IconShape', 'round');

    add('simulink/Discontinuities/Rate Limiter', 'RateLim', [1240 370 1290 410]);
    set_param([mdl '/RateLim'], ...
        'RisingSlewLimit', 'AGLAS.rate_max', ...
        'FallingSlewLimit', '-AGLAS.rate_max');

    add('simulink/Discontinuities/Saturation', 'Sat', [1330 370 1380 410]);
    set_param([mdl '/Sat'], ...
        'UpperLimit', 'AGLAS.delta_max', 'LowerLimit', '-AGLAS.delta_max');

    % ------------------------------------------------------------ logging
    % Every logged name is prefixed. An unprefixed 'moment' shadows nothing on
    % assignment but MATLAB already has a built-in moment(), so if the block
    % fails to log for any reason the later lookup silently resolves to that
    % function instead of erroring cleanly. The first run of this model hit
    % exactly that and reported "Moment requires two inputs", which says
    % nothing useful about the real problem.
    logs = { 'LogMoment', [430 200 490 230],   'aglas_moment'
             'LogTip',    [430 150 490 180],   'aglas_tip'
             'LogDelta',  [1430 370 1490 400], 'aglas_delta_cmd'
             'LogTheta',  [1180 550 1240 580], 'aglas_theta'
             'LogUad',    [1180 660 1240 690], 'aglas_u_ad'
             'LogGust',   [180 120 240 150],   'aglas_gust' };
    for i = 1:size(logs,1)
        add('simulink/Sinks/To Workspace', logs{i,1}, logs{i,2});
        set_param([mdl '/' logs{i,1}], 'VariableName', logs{i,3}, ...
                  'SaveFormat', 'Structure With Time');
    end

    add('simulink/Signal Routing/Demux', 'PerfOut', [400 180 405 230]);
    set_param([mdl '/PerfOut'], 'Outputs', '2');

    add('simulink/Sinks/Scope', 'Scope', [1430 250 1470 290]);

    % ------------------------------------------------------------ wiring
    cn = @(a, ap, b, bp) add_line(mdl, sprintf('%s/%d', a, ap), ...
                                        sprintf('%s/%d', b, bp), ...
                                        'autorouting', 'on');

    cn('Sat', 1, 'PlantIn', 1);
    cn('Gust', 1, 'PlantIn', 2);
    cn('Gust', 1, 'LogGust', 1);
    cn('PlantIn', 1, 'Plant', 1);
    cn('Plant', 1, 'PlantOut', 1);

    cn('PlantOut', 1, 'EstIn', 2);        % measurements y
    cn('Sat', 1, 'EstIn', 1);             % control into the estimator
    cn('EstIn', 1, 'Estimator', 1);

    cn('PlantOut', 2, 'PerfOut', 1);      % performance outputs z
    cn('PerfOut', 1, 'LogMoment', 1);
    cn('PerfOut', 2, 'LogTip', 1);
    cn('PerfOut', 1, 'Scope', 1);

    cn('Estimator', 1, 'PickStruct', 1);
    cn('Estimator', 1, 'PickGust', 1);
    cn('Estimator', 1, 'Kgain', 1);

    cn('PickGust', 1, 'RefModel', 1);

    cn('Estimator', 1, 'AdaptIn', 1);
    cn('RefModel', 1, 'AdaptIn', 2);
    cn('ThetaInt', 1, 'AdaptIn', 3);
    cn('AdaptIn', 1, 'AdaptLaw', 1);
    cn('AdaptLaw', 1, 'ThetaInt', 1);
    cn('ThetaInt', 1, 'LogTheta', 1);

    cn('ThetaInt', 1, 'UadIn', 1);
    cn('PickStruct', 1, 'UadIn', 2);
    cn('UadIn', 1, 'Uadaptive', 1);
    cn('Uadaptive', 1, 'AdaptOn', 1);
    cn('AdaptOn', 1, 'LogUad', 1);

    cn('Kgain', 1, 'SumU', 1);
    cn('AdaptOn', 1, 'SumU', 2);
    cn('SumU', 1, 'RateLim', 1);
    cn('RateLim', 1, 'Sat', 1);
    cn('Sat', 1, 'LogDelta', 1);

    % ------------------------------------------------------------ solver
    set_param(mdl, 'Solver', 'ode4', ...
                   'SolverType', 'Fixed-step', ...
                   'FixedStep', 'AGLAS.dt', ...
                   'StartTime', '0', ...
                   'StopTime', 'AGLAS.t_final', ...
                   'SaveOutput', 'off', ...
                   'ReturnWorkspaceOutputs', 'on');

    save_system(mdl);
    open_system(mdl);

    fprintf('Built %s.slx\n', mdl);
    fprintf('  set AGLAS.adapt_on to 0 for plain LQG, 1 for MRAC augmentation\n');
    fprintf('  run: sim(''%s'')\n', mdl);
    fprintf('  then compare against the verified .m reference with compare_simulink.m\n');
end
